apiVersion: v1
kind: Service
metadata:
  name: razor-frontend
spec:
  selector:
    pod: razor-frontend-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer # Change to ClusterIP later