apiVersion: v1
kind: Service
metadata:
  name: robot-worker-discovery
spec:
  selector:
    pod: robot-worker-discovery-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer # Change to ClusterIP later