apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot-worker-discovery
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: robot-worker-discovery-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        pod: robot-worker-discovery-pod
    spec:
      containers:
      - name: robot-worker-discovery-container
        image: mhoelzl/robot-worker-discovery:0.0.1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
